site_name: "task-runner-doc"
site_description: "Documentation for TaskRunner"

nav:
  - Introduction: index.md
  - 'API Documentation':
        - 'TaskRunner': './Api/TaskRunner/index.md'
        - 'TaskRunner.Test': './Api/TaskRunner.Test/index.md'

plugins:
  - techdocs-core
