site_name: "task-runner-doc"
site_description: "Documentation for TaskRunner"

nav:
  - Introduction: index.md
  - Api: ./Api/index.md
  - 'User Guide':
        - 'Writing your docs': 'writing-your-docs.md'
        - 'Styling your docs': 'styling-your-docs.md'

plugins:
  - techdocs-core
