name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Generate XML documentation
      run: dotnet build --configuration Release /p:GenerateDocumentationFile=true /p:NoWarn=1591

    - name: Install techdocs-cli
      run: sudo npm install -g @techdocs/cli

    - name: Install mkdocs and mkdocs plugins
      run: python -m pip install mkdocs-techdocs-core==1.*

    - name: Generate docs site
      run: techdocs-cli generate --no-docker --verbose --source-dir .TaskRunner/bin/Release/net7.0/TaskRunner.xml --output-dir .docs
    
    - name: Publish Markdown documentation
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git add docs
        git commit -m "Update Markdown documentation" || true
        git push






