name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Generate XML documentation
      run: dotnet build --configuration Release /p:GenerateDocumentationFile=true /p:NoWarn=1591

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Xml2Markdown
      run: |
        python -m pip install xml2markdown

    - name: Convert XML documentation to Markdown
      run: |
        python -m xml2markdown -i path/to/your/xml/documentation -o path/to/markdown/output
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git add path/to/markdown/output
        git commit -m "Update Markdown documentation" || true
        git push
