name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install DocFX
      run: dotnet tool install --global docfx    
    
    - name: Inicialization DocFX
      run: docfx init -q

    - name: Extract metadata
      working-directory: ./docfx_project
      run: docfx metadata
      
    - name: Build
      working-directory: ./docfx_project
      run: docfx build      
      
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docfx_project/_site
