name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Generate XML documentation
      run: dotnet build --configuration Release /p:GenerateDocumentationFile=true /p:NoWarn=1591

    - name: Setup DocFX
      run: |
        wget -qO- https://github.com/dotnet/docfx/releases/latest/download/docfx.zip | bsdtar -xvf- -C /usr/local/bin

    - name: Convert XML documentation to Markdown
      run: |
        docfx metadata -f TaskRunner.csproj -o docs
        git config --global user.email "petr.ondra@rtprocessing.com"
        git config --global user.name "GitHub Action Bot"
        git add docs
        git commit -m "Update Markdown documentation" || true
        git push
