name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dir
      run: dir
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Install DocFX
      run: dotnet tool install --global docfx           

    - name: Extract metadata
      run: docfx metadata
      
    - name: Build
      run: docfx build      
      
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_PAT }}
        publish_dir: ./_site
